# Site settings
name: Tajok Blog.
email: jou_taojian@163.com
author: Tajok
url: http://www.tajok.com
resume_site: http://www.tajok.com/resume.io/
github: http://github.com/joutaojian/
baseurl: ""
description: 
meta_description: 周韬健;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: Tajok Blog.
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: joutaojian
highlighter: rouge

# Build settings
markdown: kramdown