# Permalinks
permalink:           pretty

# Setup
title:               Tajok
tagline:             New Blog! New Start!
url:                 http://github.com/joutaojian
paginate:            1
baseurl:             "http://joutaojian.github.io"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tajok
  url:               http://joutaojian.github.io
  email:             joutaojian@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/joutaojian

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
